/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 cookie.gltf 
Author: Ziaraallman_3D (https://sketchfab.com/Ziaraallman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chocolate-chip-cookie-6ece4a093c654dfe97deabcb42e08b92
Title: Chocolate Chip Cookie
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cookie.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.lambert2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cookie.gltf')
